spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_app_dev?serverTimezone=Europe/Stockholm
    username: recipe_app_dev_user
    password: pass
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true